export const budgetData = {
  "title": "PROPOSTA COMERCIAL: THE FORCE & BETANO",
  "description": "JOB: Ativação Betano - LOCAL: Estação Sé - SP - CONTATO: Patricia - PERÍODO: Período de 7 dias (datas a definir)",
  "observacoes": "Montagem em 1 dia; Funcionamento por 7 dias; Desmontagem em 1 dia",
  "dataApresentacao": "31/7/2025",
  "categories": [
    {
      "id": "1",
      "name": "1. ESPAÇO E LICENÇAS",
      "description": "Custos relacionados ao espaço físico e licenças",
      "items": [
        {
          "id": "1.1",
          "description": "Locação Espaço Estação Sé",
          "detailedDescription": "Locação do espaço na Estação Sé do Metrô para instalação do estande de ativação da Betano, com alto fluxo",
          "status": true,
          "quantity": 0,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "2",
      "name": "2. INFRAESTRUTURA E PRODUÇÃO",
      "description": "Custos de produção e infraestrutura",
      "items": [
        {
          "id": "2.1",
          "description": "Distribuição Elétrica",
          "detailedDescription": "Infraestrutura elétrica para distribuição de energia durante a ativação, incluindo nobreaks e cabeamento",
          "status": true,
          "quantity": 5,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.2",
          "description": "Gerador",
          "detailedDescription": "Gerador ou bateria",
          "status": true,
          "quantity": 0,
          "days": 0,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.3",
          "description": "Fila",
          "detailedDescription": "Organizadores e controle de filas para gerenciar o fluxo de participantes.",
          "status": true,
          "quantity": 10,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.4",
          "description": "Alimentação",
          "detailedDescription": "Alimentação para a equipe durante a montagem, operação e desmontagem.",
          "status": true,
          "quantity": 12,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.5",
          "description": "Água",
          "detailedDescription": "Fornecimento de água potável para a equipe durante a operação.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 7,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.6",
          "description": "Custos Diversos",
          "detailedDescription": "Combustível, taxi, motoboy, impressões, materiais de escritório, comunicação e uniformes.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.7",
          "description": "Item não especificado",
          "detailedDescription": "Não informado no documento.",
          "status": true,
          "quantity": 1,
          "days": 5,
          "frequency": 1,
          "unitPrice": 25000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.8",
          "description": "Montagem e Desmontagem e Logística",
          "detailedDescription": "Montagem completa do estande, incluindo instalação, totens e sistema de LED.",
          "status": true,
          "quantity": 1,
          "days": 2,
          "frequency": 1,
          "unitPrice": 15000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.9",
          "description": "Transporte de Equipamentos",
          "detailedDescription": "Transporte especializado de todos os equipamentos e materiais, com seguro e equipe dedicada.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 18000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "2.10",
          "description": "Testes",
          "detailedDescription": "Testes completos de todos os sistemas, equipamentos e simulações de operação.",
          "status": true,
          "quantity": 1,
          "days": 2,
          "frequency": 1,
          "unitPrice": 12000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "3",
      "name": "3. CENOGRAFIA",
      "description": "Estruturas cenográficas e visuais",
      "items": [
        {
          "id": "3.2",
          "description": "Estande Promocional",
          "detailedDescription": "Estrutura cenográfica com design Betano que transforma o espaço, incluindo áreas de cadastro e prêmios.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "3.3",
          "description": "Sistema de Iluminação LED",
          "detailedDescription": "Displays LED contínuos com controle DMX, iluminação ambiente e efeitos especiais sincronizados.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "3.4",
          "description": "Balcão com chave",
          "detailedDescription": "Balcão com chave",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "3.5",
          "description": "Sistema de Energia",
          "detailedDescription": "Infraestrutura de energia dedicada para alimentar a estrutura de impacto visual.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "4",
      "name": "4. TECNOLOGIA E SUPORTE",
      "description": "Equipamentos tecnológicos e suporte técnico",
      "items": [
        {
          "id": "4.1",
          "description": "Totens Touchscreen 55\"",
          "detailedDescription": "Totens touchscreen para registro de usuários, com sistema operacional customizado e geração de códigos.",
          "status": true,
          "quantity": 4,
          "days": 7,
          "frequency": 1,
          "unitPrice": 15000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.2",
          "description": "Sistema de Cadastro",
          "detailedDescription": "Software de cadastro integrado com QR/WhatsApp, offline e com verificação em tempo real.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 45000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.3",
          "description": "Impressoras de Tickets",
          "detailedDescription": "Impressoras térmicas integradas para emissão de tickets com códigos únicos e QR codes.",
          "status": true,
          "quantity": 4,
          "days": 7,
          "frequency": 1,
          "unitPrice": 3500,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.4",
          "description": "Conectividade e Rede",
          "detailedDescription": "Infraestrutura de rede para os totens, com roteadores, switches.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 8000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.5",
          "description": "Suporte Técnico On-site",
          "detailedDescription": "Técnico especializado para manutenção preventiva e resolução de problemas durante a operação.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 150,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.6",
          "description": "Monitoramento Remoto",
          "detailedDescription": "Monitoramento remoto 24/7 dos equipamentos, com alertas automáticos e suporte técnico.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 800,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.7",
          "description": "Backup de Equipamentos",
          "detailedDescription": "Equipamentos de backup para totens, som, impressoras e componentes críticos.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 1500,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.8",
          "description": "Relatórios de Performance",
          "detailedDescription": "Relatórios detalhados de performance e métricas de participação em tempo real.",
          "status": true,
          "quantity": 7,
          "days": 1,
          "frequency": 1,
          "unitPrice": 200,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.9",
          "description": "Painel de LED (Estande de Apostas)",
          "detailedDescription": "Painel de LED de alta definição para o estande de apostas, exibindo conteúdo interativo e odds.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 8000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.10",
          "description": "Telas 85\" (Estande de Prêmios)",
          "detailedDescription": "Quatro telas de 85 polegadas para o estande de retirada de prêmios, exibindo informações e conteúdos promocionais.",
          "status": true,
          "quantity": 4,
          "days": 7,
          "frequency": 1,
          "unitPrice": 2000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.11",
          "description": "Tablets para Promotores",
          "detailedDescription": "Tablets com câmera, suporte e carregador.",
          "status": true,
          "quantity": 8,
          "days": 7,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "4.12",
          "description": "Rádios Comunicadores",
          "detailedDescription": "HTs para comunicação da equipe.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 3520,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "5",
      "name": "5. EXPERIÊNCIA DE JOGO",
      "description": "Produção de conteúdo e sistema de jogo",
      "items": [
        {
          "id": "5.1",
          "description": "Produção de Vídeos da Roleta",
          "detailedDescription": "Produção de vídeos únicos de 30 segundos com física realista e branding integrado.",
          "status": true,
          "quantity": 504,
          "days": 1,
          "frequency": 1,
          "unitPrice": 450,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "5.2",
          "description": "Sistema de Reprodução",
          "detailedDescription": "Media server profissional com ciclos de 5 minutos e cronômetros integrados.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 25000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "5.3",
          "description": "Conteúdo Promocional",
          "detailedDescription": "Vídeos promocionais para o período de cadastro e cronômetro regressivo (4:30m).",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 35000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "5.4",
          "description": "Sistema de Áudio",
          "detailedDescription": "Sistema de som ambiente com trilha sonora customizada e efeitos da roleta.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 1200,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "6",
      "name": "6. BRINDES",
      "description": "Prêmios e brindes para distribuição",
      "items": [
        {
          "id": "6.1",
          "description": "Fones Bluetooth",
          "detailedDescription": "Fones de ouvido personalizados distribuídos para participantes que acertarem números específicos.",
          "status": true,
          "quantity": 555,
          "days": 1,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "6.2",
          "description": "Copos Betano",
          "detailedDescription": "Copos personalizados distribuídos para participantes que acertarem a cor na roleta.",
          "status": true,
          "quantity": 1660,
          "days": 1,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "6.3",
          "description": "Cordões de Celular",
          "detailedDescription": "Cordões exclusivos distribuídos para participantes que acertarem par ou ímpar na roleta.",
          "status": true,
          "quantity": 1110,
          "days": 1,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "6.4",
          "description": "Chaveiros Exclusivos",
          "detailedDescription": "Chaveiros distribuídos como prêmio de consolação garantindo 100% de premiação.",
          "status": true,
          "quantity": 20000,
          "days": 1,
          "frequency": 1,
          "unitPrice": 0,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "7",
      "name": "7. EQUIPE E SERVIÇOS",
      "description": "Pessoal e serviços operacionais",
      "items": [
        {
          "id": "7.1",
          "description": "Coordenador Geral",
          "detailedDescription": "Responsável pela coordenação geral da operação e gestão da equipe.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 120,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.2",
          "description": "Promotores Volantes",
          "detailedDescription": "Promotores equipados com tablets para abordagem ativa dos passageiros.",
          "status": true,
          "quantity": 2,
          "days": 7,
          "frequency": 1,
          "unitPrice": 80,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.3",
          "description": "Operadores de Totem",
          "detailedDescription": "Operadores especializados para auxiliar no cadastro e gerenciar filas.",
          "status": true,
          "quantity": 4,
          "days": 7,
          "frequency": 1,
          "unitPrice": 70,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.4",
          "description": "Atendentes Distribuição",
          "detailedDescription": "Atendentes especializados na distribuição de prêmios e verificação de tickets.",
          "status": true,
          "quantity": 2,
          "days": 7,
          "frequency": 1,
          "unitPrice": 65,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.5",
          "description": "Auxiliar de Limpeza",
          "detailedDescription": "Responsável pela limpeza, sanitização e organização do estande.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 45,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.6",
          "description": "Bombeiro Civil",
          "detailedDescription": "Bombeiro certificado para garantir segurança, controlar fluxo e atender emergências.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 90,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.7",
          "description": "Tablets para Promotores (App)",
          "detailedDescription": "Tablets com aplicativo customizado para uso dos promotores.",
          "status": true,
          "quantity": 2,
          "days": 7,
          "frequency": 1,
          "unitPrice": 1200,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.8",
          "description": "Carregadores",
          "detailedDescription": "Equipe para montagem e desmontagem dos equipamentos.",
          "status": true,
          "quantity": 6,
          "days": 7,
          "frequency": 1,
          "unitPrice": 250,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.9",
          "description": "Limpeza",
          "detailedDescription": "Serviço de limpeza durante montagem, evento e desmontagem.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 10038.17,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.10",
          "description": "Segurança",
          "detailedDescription": "Serviço de segurança para montagem, evento e desmontagem.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 38556.69,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.12",
          "description": "Brigadista",
          "detailedDescription": "Profissional brigadista para emergências.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 133,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.14",
          "description": "Extintores",
          "detailedDescription": "Extintores para segurança contra incêndios.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 3360,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.15",
          "description": "Técnico",
          "detailedDescription": "Acompanhamento técnico na instalação.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 22000,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "7.16",
          "description": "Monitores",
          "detailedDescription": "Supervisão da operação e agendamento.",
          "status": true,
          "quantity": 1,
          "days": 1,
          "frequency": 1,
          "unitPrice": 26400,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
    {
      "id": "8",
      "name": "8. TAXAS E COMPLIANCE",
      "description": "Seguros e documentação legal",
      "items": [
        {
          "id": "8.1",
          "description": "Seguro",
          "detailedDescription": "Seguro de responsabilidade civil e acidentes pessoais.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 227.27,
          "supplier": "",
          "invoice": "",
          "notes": ""
        },
        {
          "id": "8.2",
          "description": "ART e AVCB",
          "detailedDescription": "Taxas de ART e AVCB necessárias para a execução do projeto.",
          "status": true,
          "quantity": 1,
          "days": 7,
          "frequency": 1,
          "unitPrice": 90.91,
          "supplier": "",
          "invoice": "",
          "notes": ""
        }
      ]
    },
  ],
  "totals": {
    "categorias": 3671718.35,
    "planejamento": 55075.78,
    "criacao": 55075.78,
    "honorarios": 367171.83,
    "impostos": 663112.33,
    "geral": 4812154.07
  },
  "summary": {
    "totalItems": 49,
    "totalCategories": 7,
    "activeItems": 49,
    "currency": "BRL",
    "lastUpdated": "31/07/2025"
  },
  "condicoesComerciais": [
    "1. Os direitos autorais deste projeto pertencem a THE FORCE.CC e serão remunerados pelos honorários que constam nesta planilha.",
    "2. Todos os custos são orçados, podendo haver alterações conforme mudanças de projeto após sua aprovação.",
    "3. Eventuais licenças, autorizações e taxas junto à Prefeitura serão negociadas após aprovação deste projeto.",
    "4. Os custos de criação e editoração incluem até 2 (duas) refações. A partir da 3ª refação, se esta ocorrer por responsabilidade ou vontade do cliente, será cobrada taxa de 50% dos custos referentes à criação e/ou editoração dos lay-outs refeitos.",
    "5. No caso de mudança de briefing, será cobrado 100% do custo de criação.",
    "6. A assinatura desta planilha implica na contratação dos serviços nela descritos.",
    "7. Este documento possui o valor de título jurídico extrajudicial.",
    "8. Os valores desta planilha contemplam os impostos vigentes na data de sua emissão. Caso ocorra modificações na legislação tributária que acarrete um aumento dessa carga tributária até a data de realização do evento, será emitido faturamento complementar para cobrir eventuais diferenças de custos causados por majorações de impostos."
  ]
}